version: '3' 

services:

  nginx:
    image: nginx:alpine
    links:
      - app
    volumes:
      - nextcloud:/var/www/html
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
      - letsencrypt
      - nextcloud_network
    environment:
      - VIRTUAL_HOST=graulicht-phatgatmasta.de
      - LETSENCRYPT_HOST=graulicht-phatgatmasta.de
      - LETSENCRYPT_EMAIL=maxstrasser@gmx.de

        # letsencrypt:
        #   image: jrcs/letsencrypt-nginx-proxy-companion
        #   container_name: nextcloud-letsencrypt
        #   depends_on:
        #     - nginx
        #   networks:
        #     - proxy
        #     - nextcloud_network
        #   volumes:
        #     - ../nginx-proxy/proxy/certs:/etc/nginx/certs:rw
        #     - ../nginx-proxy/proxy/vhost.d:/etc/nginx/vhost.d:rw
        #     - ./usr/share/nginx/html:/usr/share/nginx/html
        #     - /etc/localtime:/etc/localtime:ro
        #     - /var/run/docker.sock:/var/run/docker.sock:ro
        #   restart: always

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
  proxy:
    external: true
  letsencrypt:
    external: true
